P_8_1270857/Controllers/ReportsController.cs
using CrystalDecisions.CrystalReports.Engine;
using P_8_1270857.Models;
using P_8_1270857.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace P_8_1270857.Controllers
{
    public class ReportsController : Controller
    {
        CandidateDbContext db = new CandidateDbContext();
        // GET: Reports
        public ActionResult Index()
        {

            return View(db.Candidates.ToList()); ;
        }
        public ActionResult QualificationReport()
        {
            var data = db.Qualifications.Include(x => x.Candidate).Select(x => new QualificationReportModel
            {
                CandidateName = x.Candidate.CandidateName,
                CandidateId = x.CandidateId,
                Degree = x.Degree,
                PassingYear = x.PassingYear,
                Result = x.Result,
                Institute = x.Institute
            }).ToList();
            return View(data);
        }
        public ActionResult CandidatePDF()
        {
            var data = db.Candidates.AsEnumerable().Select(x => new CandidateViewModel
            {
                CandidateId = x.CandidateId,
                CandidateName = x.CandidateName,
                AppliedFor = x.AppliedFor,
                BirthDate = x.BirthDate,
                ExpectedSalary = x.ExpectedSalary,
                Picture = x.Picture,
                Image = System.IO.File.ReadAllBytes(System.IO.Path.Combine(Server.MapPath("~/Pictures"), x.Picture))
            })
                .ToList();
            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport1.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "Candidates.pdf");

        }
        public ActionResult QualificationPDF()
        {
            var data = db.Qualifications.Include(x => x.Candidate).Select(x => new QualificationReportModel
            {
                CandidateName = x.Candidate.CandidateName,
                CandidateId = x.CandidateId,
                Degree = x.Degree,
                PassingYear = x.PassingYear,
                Result = x.Result,
                Institute = x.Institute
            }).ToList();
            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport2.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "Qualifaction.pdf");
        }
    }


}

P_8_1270857/Views/Reports/Index.cshtml
@model IEnumerable<P_8_1270857.Models.Candidate>
@{
    ViewBag.Title = "Index";

}

<div class="row">
    <div class="col-12">
        <h3>Candidates</h3>

        <table class="table table-bordered">
            <thead class="table-light">
                <tr>
                    <th></th>
                    <th>Candidate Name</th>
                    <th>Date of birth</th>
                    <th>Applied For</th>
                    <th>Expected Salary</th>
                    <th>Agree to Work from home?</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var c in Model)
                {
                    <tr id="tr_@c.CandidateId" style="vertical-align:middle">
                        <td>
                            <img class="rounded-circle" src="~/Pictures/@c.Picture" style="width:40px" />
                        </td>
                        <td>@c.CandidateName</td>
                        <td>@c.BirthDate.ToString("yyyy-MM-dd")</td>
                        <td>@c.AppliedFor</td>
                        <td>@c.ExpectedSalary.ToString("0.00")</td>
                        <td>@(c.WorkFromHome ? "Yes": "No")</td>

                    </tr>

                }
            </tbody>
        </table>
    </div>
    <div class="col-12 text-center">
        @Html.ActionLink("To PDF", "CandidatePDF", "Reports", new { }, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>

P_8_1270857/Views/Reports/QualificationPDF.cshtml
@model IEnumerable<P_8_1270857.ViewModels.QualificationReportModel>
@{
    ViewBag.Title = "Index";

}

<div class="row">
    <div class="col-12">
        <h3>Candidates</h3>

        <table class="table table-bordered">
            <thead class="table-light">
                <tr>

                    <th>Candidate Name</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var g in Model.GroupBy(x => x.CandidateName).ToList())
                {
                    <tr>
                        <td>
                            @g.Key
                        </td>

                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td colspan="6">
                            <h4>Qualifications</h4>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Degree</th>
                                        <th>Passing Year</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var q in g)
                                    {
                                        <tr>
                                            <td>@q.Degree</td>
                                            <td>@q.Institute</td>
                                            <td>@q.PassingYear</td>
                                            <td>@q.Result</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-12 text-center">
        @Html.ActionLink("To PDF", "QualificationPDF", "Reports", new { }, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>
@section scripts {

}

P_8_1270857/Views/Reports/QualificationReport.cshtml
@model IEnumerable<P_8_1270857.ViewModels.QualificationReportModel>
@{
    ViewBag.Title = "QualificationReport";

}

<div class="row">
    <div class="col-12">
        <h3>Candidates</h3>

        <table class="table table-bordered">
            <thead class="table-light">
                <tr>

                    <th>Candidate Name</th>

                </tr>
            </thead>
            <tbody>
                @foreach (var g in Model.GroupBy(x => x.CandidateName).ToList())
                {
                    <tr>
                        <td>
                            @g.Key
                        </td>

                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td colspan="6">
                            <h4>Qualifications</h4>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th>Degree</th>
                                        <th>Passing Year</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var q in g)
                                    {
                                        <tr>
                                            <td>@q.Degree</td>
                                            <td>@q.Institute</td>
                                            <td>@q.PassingYear</td>
                                            <td>@q.Result</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-12 text-center">
        @Html.ActionLink("To PDF", "QualificationPDF", "Reports", new { }, new { @class = "btn btn-primary btn-sm" })
    </div>
</div>
@section scripts {

}