P_8_1270857/Controllers/CandidatesController.cs
using P_8_1270857.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using P_8_1270857.ViewModels;

namespace P_8_1270857.Controllers
{
    public class CandidatesController : Controller
    {
        CandidateDbContext db = new CandidateDbContext();
        // GET: Candidates
        public ActionResult Index()
        {
            return View(db.Candidates.Include(x => x.Qualifications).ToList());
        }
        // CREATE
       // ////////////////////////////
        // 
        public ActionResult Create()
        {
            ViewBag.PostList = new List<SelectListItem>
            {
                new SelectListItem{ Text="Select", Value="", Selected=true},
                new SelectListItem{Text="Executive", Value="Executive"},
                new SelectListItem{Text="Marketing Executive", Value="Marketing Executive"},
                new SelectListItem{Text="Bell boy", Value="Bell boy"}
            };
            return View();
        }

        [HttpPost]
        public ActionResult Create(CandidateInputModel data)
        {
            if (ModelState.IsValid)
            {
                Candidate c = new Candidate
                {
                    CandidateName = data.CandidateName,
                    BirthDate = data.BirthDate,
                    AppliedFor = data.AppliedFor,
                    ExpectedSalary = data.ExpectedSalary,
                    WorkFromHome = data.WorkFromHome,
                    Picture = data.Picture
                };
                foreach (var q in data.Qualifications)
                {
                    c.Qualifications.Add(q);
                }
                db.Candidates.Add(c);
                db.SaveChanges();
                return Json(new { id = c.CandidateId });
            }
            return Json(null);
        }
        public PartialViewResult AddQuationToForm(CandidateInputModel c = null, int? index = null)
        {
            if (c == null) c = new CandidateInputModel();
            if (index.HasValue)
            {
                if (index < c.Qualifications.Count)
                {
                    c.Qualifications.RemoveAt(index.Value);
                }
            }
            else
            {
                c.Qualifications.Add(new Qualification());
            }

            return PartialView("_QualificationForm", c);
        }
        public ActionResult UploadImage(int id, ImageUpload pic)
        {
            if (ModelState.IsValid)
            {
                if (pic.Picture != null)
                {
                    Candidate c = db.Candidates.First(x => x.CandidateId == id);
                    string ext = Path.GetExtension(pic.Picture.FileName);
                    string fileName = Path.GetFileNameWithoutExtension(Path.GetRandomFileName()) + ext;
                    string savePath = Path.Combine(Server.MapPath("~/Pictures"), fileName);
                    pic.Picture.SaveAs(savePath);
                    c.Picture = fileName;
                    db.SaveChanges();
                    return Json(fileName);
                }
            }
            return Json(null);
        }
        ///Create

        ////Edit
        /// ////////////////////////////////////////////////////
        ///  
        public ActionResult Edit(int id)
        {
            ViewBag.PostList = new List<SelectListItem>
            {
                new SelectListItem{ Text="Select", Value="", Selected=true},
                new SelectListItem{Text="Executive", Value="Executive"},
                new SelectListItem { Text = "Marketing Executive", Value = "Marketing Executive" },
                new SelectListItem { Text = "Bell boy", Value = "Bell boy" }
            };
            var candidate = db.Candidates.Include(c => c.Qualifications).First(c => c.CandidateId == id);

            return View(
                new CandidateEditModel
                {
                    CandidateId = candidate.CandidateId,
                    CandidateName = candidate.CandidateName,
                    BirthDate = candidate.BirthDate,
                    AppliedFor = candidate.AppliedFor,
                    ExpectedSalary = candidate.ExpectedSalary,
                    WorkFromHome = candidate.WorkFromHome,
                    Picture = candidate.Picture,
                    Qualifications = candidate.Qualifications.ToList()
                }
                );
        }
        [HttpPost]
        public ActionResult Edit(CandidateEditModel model)
        {
            var existing = db.Candidates.First(c => c.CandidateId == model.CandidateId);
            if (ModelState.IsValid)
            {
                existing.CandidateName = model.CandidateName;
                existing.BirthDate = model.BirthDate;
                existing.AppliedFor = model.AppliedFor;
                existing.WorkFromHome = model.WorkFromHome;
                existing.ExpectedSalary = model.ExpectedSalary;
                db.Qualifications.RemoveRange(existing.Qualifications.ToList());
                foreach (var q in model.Qualifications)
                {
                    q.CandidateId = existing.CandidateId;
                    db.Qualifications.Add(q);
                }
                db.SaveChanges();
                return Json(existing.CandidateId);
            }
            return Json(null);
        }
        public PartialViewResult AddQuationToEditForm(CandidateEditModel c, int? index = null)
        {

            if (index.HasValue)
            {
                if (index < c.Qualifications.Count)
                {
                    c.Qualifications.RemoveAt(index.Value);
                }
            }


            return PartialView("_QualificationEditForm", c);
        }
        public PartialViewResult AddMore(CandidateEditModel c, int? index = null)
        {
            if (c == null) c = new CandidateEditModel();
            if (index.HasValue)
            {
                if (index < c.Qualifications.Count)
                {
                    c.Qualifications.RemoveAt(index.Value);
                }
            }
            else
            {
                c.Qualifications.Add(new Qualification());
            }

            return PartialView("_QualificationEditForm", c);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var existing = db.Candidates.FirstOrDefault(c => c.CandidateId == id);
            if (existing != null)
            {
                db.Candidates.Remove(existing);
                db.SaveChanges();
                return Json(existing.CandidateId);
            }
            else
            {
                return HttpNotFound();
            }
        }
    }
}

P_8_1270857/Controllers/CrystalController.cs
using CrystalDecisions.CrystalReports.Engine;
using P_8_1270857.Models;
using P_8_1270857.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace P_8_1270857.Controllers
{
    public class CrystalController : Controller
    {
        CandidateDbContext db = new CandidateDbContext();
        // GET: Reports
        public ActionResult Index()
        {

            return View(db.Candidates.ToList()); ;
        }
        public ActionResult QualificationReport()
        {
            var data = db.Qualifications.Include(x => x.Candidate).Select(x => new QualificationReportModel
            {
                CandidateName = x.Candidate.CandidateName,
                CandidateId = x.CandidateId,
                Degree = x.Degree,
                PassingYear = x.PassingYear,
                Result = x.Result,
                Institute = x.Institute
            }).ToList();
            return View(data);
        }
        public ActionResult CandidatePDF()
        {
            var data = db.Candidates.AsEnumerable().Select(x => new CandidateViewModel
            {
                CandidateId = x.CandidateId,
                CandidateName = x.CandidateName,
                AppliedFor = x.AppliedFor,
                BirthDate = x.BirthDate,
                ExpectedSalary = x.ExpectedSalary,
                Picture = x.Picture,
                Image = System.IO.File.ReadAllBytes(System.IO.Path.Combine(Server.MapPath("~/Pictures"), x.Picture))
            })
                .ToList();
            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport1.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "Candidates.pdf");

        }
        public ActionResult QualificationPDF()
        {
            var data = db.Qualifications.Include(x => x.Candidate).Select(x => new QualificationReportModel
            {
                CandidateName = x.Candidate.CandidateName,
                CandidateId = x.CandidateId,
                Degree = x.Degree,
                PassingYear = x.PassingYear,
                Result = x.Result,
                Institute = x.Institute
            }).ToList();
            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport2.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
            stream.Seek(0, SeekOrigin.Begin);

            return File(stream, "application/pdf", "Qualifaction.pdf");
        }
        public ActionResult QualificationExcel()
        {
            var data = db.Qualifications.Include(x => x.Candidate).Select(x => new QualificationReportModel
            {
                CandidateName = x.Candidate.CandidateName,
                CandidateId = x.CandidateId,
                Degree = x.Degree,
                PassingYear = x.PassingYear,
                Result = x.Result,
                Institute = x.Institute
            }).ToList();
            ReportDocument rd = new ReportDocument();

            rd.Load(Path.Combine(Server.MapPath("~/Reports"), "CrystalReport2.rpt"));
            rd.SetDataSource(data);
            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();


            rd.PrintOptions.PaperOrientation = CrystalDecisions.Shared.PaperOrientation.Landscape;
            rd.PrintOptions.ApplyPageMargins(new CrystalDecisions.Shared.PageMargins(5, 5, 5, 5));
            rd.PrintOptions.PaperSize = CrystalDecisions.Shared.PaperSize.PaperA4;

            Stream stream = rd.ExportToStream(CrystalDecisions.Shared.ExportFormatType.Excel);
            stream.Seek(0, SeekOrigin.Begin);
            return File(stream, "application/vnd.ms-excel", "Qualifaction.xls");
        }
    }


}

P_8_1270857/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <style>
        body {
            padding-top: 70px;
        }
    </style>
    @RenderSection("styles", false)
</head>
<body>
    <nav class="navbar bg-danger navbar-expand-md fixed-top  shadow-sm border-bottom">
        <div class="container-fluid">
            <span class="navbar-brand">MVC Project<sup>8</sup></span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbar">
                <ul class="navbar-nav">
                    <li class="nav-item">@Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Master/Datil CRUD", "Index", "Candidates", new { }, new { @class = "nav-link" })</li>
                    @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Example
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Qualification", "Index", "Qualification", new { }, new { @class = "dropdown-item" })</li>

                        </ul>
                    </li>*@
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Report
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>@Html.ActionLink("Report1", "Index", "Crystal", new { }, new { @class = "dropdown-item" })</li>
                            <li>@Html.ActionLink("Report2", "QualificationReport", "Crystal", new { }, new { @class = "dropdown-item" })</li>
                        </ul>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    @if (Request.IsAuthenticated)
                    {
                        <li class="nav-item">@Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                        <li class="nav-item">@Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })</li>
                        <li class="nav-item">@Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>

    <main class="container-fluid" style="min-height:calc(100vh - 110px)">
        @RenderBody()
    </main>
    <footer class="container-fluid">
        <p>@DateTime.Today.ToString("MMM dd, yyyy")</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>